# CS 4820
# Lab 4: Understanding how a _feed-forward_ ANN works

In this lab, we are going to manually calculate the outputs of all the neurons in a multi-layer feed_forwared NN and then build a Teras model to verify our calculations.

### 0. Manually calculate the outputs from all neurons

In [3]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.activations import tanh
from tensorflow.keras.activations import sigmoid

x_test = np.array([[0.5, 1.2, 0.7]])
print("Inputs:\n", x_test)

weights_0 = np.array([[1, -1, 0], [0, 1, -1]]).T
print("Weights:\n", weights_0)

thetas_0 = np.full((2,), 0.01)
print("Thetas:\n", thetas_0)

#print(x_test.dot(weights_0)+thetas_0[0])
y_1 = tanh(x_test.dot(weights_0)+thetas_0)
print(y_1)
weights_1 = np.array([[-1, -0.8]]).T
thetas_1 = np.full((1,), 0.1)
output = sigmoid(np.dot(y_1, weights_1)+thetas_1).numpy()
print(output)

print(weights_0.shape, thetas_0.shape)
print(weights_1.shape, thetas_1.shape)

Inputs:
 [[0.5 1.2 0.7]]
Weights:
 [[ 1  0]
 [-1  1]
 [ 0 -1]]
Thetas:
 [0.01 0.01]
tf.Tensor([[-0.597982   0.4699452]], shape=(1, 2), dtype=float64)
[[0.57981789]]
(3, 2) (2,)
(2, 1) (1,)


### 1. Build a model in Keras to verify the calculations above

In [47]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

model = Sequential()

model.add(Dense(2, input_shape=(3,), activation='tanh'))
model.add(Dense(1, activation='sigmoid'))
model.compile(Adam(lr=0.1),
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.layers[0].set_weights([weights_0, thetas_0])
model.layers[1].set_weights([weights_1, thetas_1])

y_pred = model.predict(x_test)
print(y_pred)

[[0.5798179]]
