# CS 4820
# Tutorial 3: Multi-layer Neural Networks

### 1. Logic XOR

As we all know, a Perceptron is not capable of learning **logical XOR** since it's not linearly separable. Now let's build a multi-layer NN to learn it.

In [1]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# the four different states of the logical XOR operation
training_data = np.array([[0,0],[0,1],[1,0],[1,1]], "float32")

print(training_data)

# the four expected results in the same order
target_data = np.array([[0],[1],[1],[0]], "float32")

print(target_data)

model = Sequential()

model.add(Dense(16, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics=['binary_accuracy'])

model.fit(training_data, target_data, epochs=500, verbose=2, batch_size=4)

print(model.layers[0].get_weights())

print(model.layers[1].get_weights())

print("Test results:\n", model.predict(training_data))


[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
[[0.]
 [1.]
 [1.]
 [0.]]
Epoch 1/500
4/4 - 0s - loss: 0.2961 - binary_accuracy: 0.5000
Epoch 2/500
4/4 - 0s - loss: 0.2955 - binary_accuracy: 0.2500
Epoch 3/500
4/4 - 0s - loss: 0.2949 - binary_accuracy: 0.2500
Epoch 4/500
4/4 - 0s - loss: 0.2943 - binary_accuracy: 0.2500
Epoch 5/500
4/4 - 0s - loss: 0.2937 - binary_accuracy: 0.2500
Epoch 6/500
4/4 - 0s - loss: 0.2931 - binary_accuracy: 0.2500
Epoch 7/500
4/4 - 0s - loss: 0.2926 - binary_accuracy: 0.2500
Epoch 8/500
4/4 - 0s - loss: 0.2920 - binary_accuracy: 0.2500
Epoch 9/500
4/4 - 0s - loss: 0.2914 - binary_accuracy: 0.2500
Epoch 10/500
4/4 - 0s - loss: 0.2908 - binary_accuracy: 0.2500
Epoch 11/500
4/4 - 0s - loss: 0.2903 - binary_accuracy: 0.2500
Epoch 12/500
4/4 - 0s - loss: 0.2898 - binary_accuracy: 0.2500
Epoch 13/500
4/4 - 0s - loss: 0.2893 - binary_accuracy: 0.2500
Epoch 14/500
4/4 - 0s - loss: 0.2887 - binary_accuracy: 0.2500
Epoch 15/500
4/4 - 0s - loss: 0.2882 - binary_accuracy: 0.2500
Ep

Epoch 130/500
4/4 - 0s - loss: 0.2501 - binary_accuracy: 0.5000
Epoch 131/500
4/4 - 0s - loss: 0.2499 - binary_accuracy: 0.5000
Epoch 132/500
4/4 - 0s - loss: 0.2497 - binary_accuracy: 0.5000
Epoch 133/500
4/4 - 0s - loss: 0.2494 - binary_accuracy: 0.5000
Epoch 134/500
4/4 - 0s - loss: 0.2492 - binary_accuracy: 0.5000
Epoch 135/500
4/4 - 0s - loss: 0.2490 - binary_accuracy: 0.5000
Epoch 136/500
4/4 - 0s - loss: 0.2488 - binary_accuracy: 0.5000
Epoch 137/500
4/4 - 0s - loss: 0.2486 - binary_accuracy: 0.5000
Epoch 138/500
4/4 - 0s - loss: 0.2483 - binary_accuracy: 0.5000
Epoch 139/500
4/4 - 0s - loss: 0.2481 - binary_accuracy: 0.5000
Epoch 140/500
4/4 - 0s - loss: 0.2479 - binary_accuracy: 0.5000
Epoch 141/500
4/4 - 0s - loss: 0.2477 - binary_accuracy: 0.5000
Epoch 142/500
4/4 - 0s - loss: 0.2475 - binary_accuracy: 0.5000
Epoch 143/500
4/4 - 0s - loss: 0.2472 - binary_accuracy: 0.5000
Epoch 144/500
4/4 - 0s - loss: 0.2470 - binary_accuracy: 0.5000
Epoch 145/500
4/4 - 0s - loss: 0.2468 - 

4/4 - 0s - loss: 0.2205 - binary_accuracy: 0.7500
Epoch 259/500
4/4 - 0s - loss: 0.2203 - binary_accuracy: 0.7500
Epoch 260/500
4/4 - 0s - loss: 0.2200 - binary_accuracy: 0.7500
Epoch 261/500
4/4 - 0s - loss: 0.2197 - binary_accuracy: 0.7500
Epoch 262/500
4/4 - 0s - loss: 0.2195 - binary_accuracy: 0.7500
Epoch 263/500
4/4 - 0s - loss: 0.2192 - binary_accuracy: 0.7500
Epoch 264/500
4/4 - 0s - loss: 0.2190 - binary_accuracy: 0.7500
Epoch 265/500
4/4 - 0s - loss: 0.2187 - binary_accuracy: 0.7500
Epoch 266/500
4/4 - 0s - loss: 0.2185 - binary_accuracy: 0.7500
Epoch 267/500
4/4 - 0s - loss: 0.2182 - binary_accuracy: 0.7500
Epoch 268/500
4/4 - 0s - loss: 0.2179 - binary_accuracy: 0.7500
Epoch 269/500
4/4 - 0s - loss: 0.2177 - binary_accuracy: 0.7500
Epoch 270/500
4/4 - 0s - loss: 0.2174 - binary_accuracy: 0.7500
Epoch 271/500
4/4 - 0s - loss: 0.2172 - binary_accuracy: 0.7500
Epoch 272/500
4/4 - 0s - loss: 0.2169 - binary_accuracy: 0.7500
Epoch 273/500
4/4 - 0s - loss: 0.2166 - binary_accurac

Epoch 387/500
4/4 - 0s - loss: 0.1826 - binary_accuracy: 0.7500
Epoch 388/500
4/4 - 0s - loss: 0.1823 - binary_accuracy: 0.7500
Epoch 389/500
4/4 - 0s - loss: 0.1820 - binary_accuracy: 0.7500
Epoch 390/500
4/4 - 0s - loss: 0.1816 - binary_accuracy: 0.7500
Epoch 391/500
4/4 - 0s - loss: 0.1813 - binary_accuracy: 0.7500
Epoch 392/500
4/4 - 0s - loss: 0.1810 - binary_accuracy: 0.7500
Epoch 393/500
4/4 - 0s - loss: 0.1807 - binary_accuracy: 0.7500
Epoch 394/500
4/4 - 0s - loss: 0.1804 - binary_accuracy: 0.7500
Epoch 395/500
4/4 - 0s - loss: 0.1800 - binary_accuracy: 0.7500
Epoch 396/500
4/4 - 0s - loss: 0.1797 - binary_accuracy: 0.7500
Epoch 397/500
4/4 - 0s - loss: 0.1794 - binary_accuracy: 1.0000
Epoch 398/500
4/4 - 0s - loss: 0.1791 - binary_accuracy: 1.0000
Epoch 399/500
4/4 - 0s - loss: 0.1787 - binary_accuracy: 1.0000
Epoch 400/500
4/4 - 0s - loss: 0.1784 - binary_accuracy: 1.0000
Epoch 401/500
4/4 - 0s - loss: 0.1781 - binary_accuracy: 1.0000
Epoch 402/500
4/4 - 0s - loss: 0.1778 - 

Test results:
 [[0.47553444]
 [0.6715633 ]
 [0.628274  ]
 [0.32907867]]
