## Tutorial - 0
### 1. Basic Python

In [5]:
import random
for i in range(5):
    print(random.randint(10,99))

26
44
53
77
62


In [4]:
var=5
print(var)
print(type(var))

var=3.2
print(var)
print(type(var))

var='spam'
print(var)
print(type(var))

5
<class 'int'>
3.2
<class 'float'>
spam
<class 'str'>


In [6]:
mystring='ham and eggs'
print(mystring[0:5]) # note that the first index is inclusive and the secon
print(mystring.find('and'))
print(mystring.split(' '))

ham a
4
['ham', 'and', 'eggs']


In [7]:
x = 0
while x < 10:
    if x%2 == 0:
        print(x)
    x+=1
print('done')

0
2
4
6
8
done


In [10]:
mylist = [1, 2]
mylist.append("three")

print(mylist)

newlist = [1, 1, 2, 3, 5, 8, 13]
newlist[4] = 3000
print(newlist[4])
print(newlist[-1]) # get the last item in the list
newlist.pop()
print(newlist)

[1, 2, 'three']
3000
13
[1, 1, 2, 3, 3000, 8]


In [13]:
tup1 = (12, 34.56)
tup2 = ('abc', 'xyz')

try:
    tup1[0] =100;
except TypeError:
    print('See why this returns an error?')

tup3 = tup1 + tup2 # this concatenates the two tuplesprint(tup3)
print('length of tup3:', len(tup3))
for x in tup3: print(x)

See why this returns an error?
length of tup3: 4
12
34.56
abc
xyz


In [15]:
numbers= {'one': 1, 'two': 2, 'three': 3, 'four': 4 }
print(numbers['one'])
del numbers['one']  # Remove an entry from the dictionary
try:
    print(numbers['one'])
except KeyError:
    print("This shouldn't work, since we deleted numbers['one'] above")
print(numbers)
print(numbers.keys())
print(numbers.values())

1
This shouldn't work, since we deleted numbers['one'] above
{'two': 2, 'three': 3, 'four': 4}
dict_keys(['two', 'three', 'four'])
dict_values([2, 3, 4])


In [4]:
import numpy as np
d = np.array([[10], [20], [30]])
print(d)
d.shape

(3, 1)

In [10]:
c = np.array([[1, 2, 3]])
c.shape

(1, 3)

In [7]:
e = c.transpose()
e

array([[1],
       [2],
       [3]])

In [9]:
f = e.reshape(-1, 1)
f

array([[1],
       [2],
       [3]])

In [19]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [1]:
hours = 10
print("Hours:\t\t", hours)

Hours:		 10
